data:
  path: "data/raw/used_cars.csv"
  test_size: 0.2
  random_state: 42

target:
  name: "price_num"

features:
  numeric:
    - model_year
    - milage_num
  categorical:
    - brand
    - model
    - fuel_type
    - engine
    - transmission
    - ext_col
    - int_col
    - accident
    - clean_title

preprocessing:
  version: "v1"
  filter_by_quantiles: true
  price_quantiles: [0.01, 0.99]
  milage_quantiles: [0.01, 0.99]
  fillna_categorical: "Unknown"

model:
  type: "random_forest"
  params:
    n_estimators: 100      # меньше деревьев
    max_depth: 12          # ограничение глубины
    random_state: 42
    n_jobs: -1

output:
  model_path: "artifacts/models/model_v1_tuned.joblib"
  metrics_path: "artifacts/models/metrics_v1_tuned.json"

mlflow:
  enabled: true
  experiment_name: "used_cars_price"
  run_name: "rf_v1_tuned_depth12"
  tracking_uri: null